apiVersion: apps/v1
kind: Deployment
metadata:
  name: duckdb-bundle
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: app-duckdb-bundle
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: app-duckdb-bundle
        app: lakefs-ecosystem
    spec:
      containers:
        - image: buntha/duckdb-bundle:0.0.3
          imagePullPolicy: Always
          name: duckdb-bundle
          ports:
            - containerPort: 8088
---
# apiVersion: v1
# kind: Service
# metadata:
#   name: duckdb-bundle
#   labels:
#     run: my-nginx
# spec:
#   ports:
#     - port: 80
#       targetPort: 8088
#       protocol: TCP
#   type: NodePort
#   selector:
#     app.kubernetes.io/name: app-duckdb-bundle
apiVersion: v1
kind: Service
metadata:
  name: duckdb
  labels:
    run: my-nginx
    app: lakefs-ecosystem
spec:
  ports:
    - port: 80
      protocol: TCP
  selector:
    run: my-nginx
